#!/bin/sh
# strip out everything but the columns containing relig-type data where there
# there are 50 bins, beginning in the third column.

# first line removes first two columns.
# after that, there are 50 columns of relig-type data.
# second line removes 53rd column through end of line, which at this point is actually 51st through rest of line.
# (sed is not really the right tool)
sed -e 's/^[^,]*,[^,]*,//' \
    -e 's/\([^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,\).*/\1/' \
    "$@"
