#!/bin/sh
# A rather kludgey sed script.
# Given NetLogo table output from BaliPlus, in which the relig-type
# buckets are given as a string rep of a NetLogo list of length 20 
# in a single csv field, converts that field to 20 numeric fields labeled
# "bucket1", "bucket2", etc.
# Note that other lists of numbers, if they were added, would be similarly
# converted, but a new special case would have to be added for the header
# line.

sed -e 's/"normalize-buckets relig-type-years-buckets",/"bucket0","bucket1","bucket2","bucket3","bucket4","bucket5","bucket6","bucket7","bucket8","bucket9","bucket10","bucket11","bucket12","bucket13","bucket14","bucket15","bucket16","bucket17","bucket18","bucket19",/' \
    -e '8,$s/"\[/ /' \
    -e '8,$s/\]"//' \
    -e '8,$s/ \([0-9.][0-9.E-]*\)/"\1",/g'
