#!/bin/sh
# A rather kludgey sed script.
# Given NetLogo table output from BaliPlus, in which the relig-type
# buckets are given as a string rep of a NetLogo list of length 20 
# in a single csv field, converts that field to 20 numeric fields labeled
# "bucket1", "bucket2", etc.
# Note that other lists of numbers, if they were added, would be similarly
# converted, but a new special case would have to be added for the header
# line.

sed -e 's/"normalize-buckets relig-type-years-buckets",/"bin0","bin1","bin2","bin3","bin4","bin5","bin6","bin7","bin8","bin9","bin10","bin11","bin12","bin13","bin14","bin15","bin16","bin17","bin18","bin19",/' \
    -e '8,$s/"\[/ /' \
    -e '8,$s/\]",//' \
    -e '8,$s/ \([0-9.][0-9.E-]*\)/"\1",/g'
