#!/bin/sh

# Assume that src/NetLogo.jar is a link to the real NetLogo.jar.
netlogo=~/bali/src/NetLogo.jar
# netlogo="/Applications/NetLogo 5.1.0/NetLogo.jar"

if [ -z "$1" ]; then
	echo "usage: $0 <experimentname> [ --additional netlogo-args ]"
	exit 1
fi

experiment="$1"
shift

set -x
java -Xmx1024m -Dfile.encoding=UTF-8 -cp "$netlogo" org.nlogo.headless.Main \
  --model src/LKJplus/BaliPlus.nlogo \
  --experiment "$experiment" \
  --table data/"$experiment.csv" "$@"


# maybe add:
# --threads <number>: use this many threads to do model runs in parallel
# defaults to one thread per processor. 
